#ifndef __SYSTEM_TYPES_H
#define __SYSTEM_TYPES_H

typedef enum
{
	SYS_AREA_NONE,
	SYS_AREA_INIT,
	SYS_AREA_MAIN_ALGO,
	SYS_AREA_READ_SENSORS,
	SYS_AREA_PERIPH_SDCARD,
	SYS_AREA_PERIPH_RADIO,
	SYS_AREA_PERIPH_BAROM,
	SYS_AREA_PERIPH_ACC

} SystemArea;

typedef enum
{
	SYS_STATE_NONE = 0,
	SYS_STATE_INIT,
	SYS_STATE_STANDBY,
	SYS_STATE_LIFTOFF,
	SYS_STATE_ASCENT,
	SYS_STATE_APOGY,
	SYS_STATE_DESCENT,
	SYS_STATE_GROUND
} SystemState;

#define status_t uint8_t

#endif